[template.ofd]
ofdru = "ofd.ru"
firstofd = "1-ofd.ru"
conturofd = "kontur.ru"

[fields.kkt]
inn = "инн фирмы"
regnumkkt = "регистрационный номер ККТ"
zavnumkkt = "заводской номер ККТ"
fnkkt = "номер ФН"
nameofkkt = "имя ККТ в ОФД"

[fields.check]
numSm = "номер смены"
fd = "номер ФД"
fp = "фискальный номер чека"
amountCheck = "сумма чека"
nal = "сумма наличными"
bez = "сумма безналичными"
credit = "сумма в расрочку"
avance = "сумма зачета апанса"
vsreshpredst = "сумма встречным представлением"
kassir = "имя кассира"
innkassir = "инн кассира"
date = "дата чека"
time = "время чека"
osn = "система налогообложения чека"
tag1054 = "тип чека: приход, расход, возврат прихода, возврат расхода"
tpyeCheck = "чек, коррекция и прочие"
link = "ссылка чека"

[fields.positions]
name = "название товара"
quantity = "количество товара"
price = "цена товара"
amountpos = "сумма товара"
predm = "предмет расчета"
spos = "способ расчета"
stavkaNDS = "ставка НДС"
mark = "марка"
bindfild = "поле для связки с таблицей чеков. может быть ФД, ФП, наименование кассы, рег номер кассы"

[conturofd]
#-colFNCh 0 -colKassaNameCh 1 -colFDCh 2 -colFPCh 3 -col_kassir 4 -colDate 5 -colTypeCheck 6 -colTypeOper 7 -colNal 8 -colBez 9 -colAvPay 10 -colCred 11 -colObm 12 -colSumNDS20 13
fnkkt = "ФН №"
nameofkkt = "Касса"

fd = "ФД №"
amountCheck = ""
nal = "Наличными"
bez = "Безналичными"
credit = "Кредит"
avance = "Аванс"
vsreshpredst = "Обмен"
kassir = "Кассир"
date = "Дата чека"
osn = "СНО"
tag1054 = "Тип операции"
tpyeCheck = "Тип чека"

name = "Товар. Услуга"
quantity = "Кол-во"
price = "Цена, ₽"
amountpos = "Сумма, ₽"
stavkaNDS = "#inv$НДС 20%;НДС 20/120;НДС 10%;НДС 10/110;Сумма с НДС 0%"

bindfildfromheader = "nameofkkt"
bindfildfromtable = "Название кассы"

[firstofd]
#-colFNCh 5 -colRegCh 2 -colKassaNameCh -1 -colFDCh 14 -colFPCh 15 -col_kassir 11 -col_Inn_kassir 12 -colDate 16 -colTypeCheck -1 -colTypeOper 19 -colNal 32 -colBez 33 -colAvPay 34 -colCred 35 -colObm 36 -colSumNDS20 28 -colName 6 -colQuant 8 -colPrice 7 -colAmountPos 9 -colSummPrepay -1 -colKassaNamePos 0 -colFDPos -1 -colPred 5
regnumkkt = "Регистрационный номер ККТ (1037)"
fnkkt = "Номер ФН (1041)"

#numSm = "Номер смены (1038)"
fd = "Номер ФД (1040)"
fp = "ФПД (1077)"
amountCheck = "Сумма расчета по чеку без НДС (1105)"
nal = "Сумма по чеку (БСО) наличными (1031)"
bez = "Сумма по чеку (БСО) безналичными (1081)"
credit = "Сумма по чеку (БСО) постоплатой (в кредит) (1216)"
avance = "Сумма по чеку (БСО) предоплатой (зачетом аванса и (или) предыдущих платежей) (1215)"
vsreshpredst = "Сумма по чеку (БСО) встречным предоставлением (1217)"
kassir = "Кассир (1021)"
innkassir = "ИНН кассира (1203)"
date = "Дата, время (1012)"
osn = "Применяемая система налогообложения (1055)"
tag1054 = "Тип документа. Признак расчета (1054)"

name = "Наименование предмета расчета (1030)"
quantity = "Количество предмета расчета (1023)"
price = "Стоимость предмета расчета с учетом скидок и наценок (1043)"
amountpos = "Сумма расчета, указанного в чеке (БСО) (1020)"
predm = "Признак предмета расчета (1212)"
spos = "#inv$Предоплата 100%;Частичная предоплата;Аванс;Полный расчет;Частичный расчет и кредит;Оплата кредита"
stavkaNDS = "#inv$Сумма расчета по чеку с НДС по ставке 0% (1104);Сумма НДС чека по ставке 10% (1103);Сумма НДС чека по ставке 20% (1102);Сумма НДС чека по расч. ставке 10/110 (1107);Сумма НДС чека по расч. ставке 20/120 (1106)"

bindfildfromheader = "regnumkkt"
bindfildfromtable = "#analyse$Номер чека"

[ofdru]
#-colFNCh 1 -colRegCh 0 -colKassaNameCh -1 -colFDCh 15 -colFPCh -1 -col_kassir -1 -col_Inn_kassir -1 -colDate 16 -colTypeCheck -1 -colTypeOper -1 -colNal -1 -colBez -1 -colAvPay -1 -colCred -1 -colObm -1 -colSumNDS20 -1 -colName 0 -colQuant 5 -colPrice 4 -colAmountPos 6 -colSummPrepay -1 -colKassaNamePos 22 -colFDPos 32 -colPred 1 -colSpsRash 3 -colFPTovTabl 11 -col_kassirTov 28 -col_Inn_kassirTov -1 -colTypeCheckTov 2 -colNalTob 12 -colBezTov 13 -colAvPayTov 14 -colCredTov 15 -colObmTov 16 -colLinkOnCheck 30
regnumkkt = "Регистрационный номер ККТ"
fnkkt = "Заводской номер ФН"

fd = "Номер ФД"
fp = "#inv$ФПД"
nal = "#inv#analyse$Расчет по чеку наличными (тег 1031)"
bez = "#inv#analyse$Расчет по чеку безналичными (тег 1081)"
credit = "#inv#analyse$Расчет по чеку с постоплатой (тег 1216)"
avance = "#inv#analyse$Расчет по чеку предоплатой / зачетом аванса (тег 1215)"
vsreshpredst = "#inv#analyse$Расчет по чеку встречным предоставлением (тег 1217)"
kassir = "#inv$Кассир"
date = "Дата создания документа"
osn = "#analyse:link"
tag1054 = "#inv$Признак расчета (тег 1054)"
link = "#inv$Ссылка на документ"

name = "Наименование товаров и услуг (тег 1030)"
quantity = "Количество предметов расчета (тег 1023)"
price = "Цена за единицу предмета расчета с учетом скидок и наценок (тег 1079)"
amountpos = "Стоимость предмета расчета с учетом скидок и наценок (тег 1043)"
predm = "Признак предмета расчета (тег 1212)"
spos = "Признак способа расчета (тег 1214)"
stavkaNDS = "Сумма НДС 0%, руб. (тег 1104);Сумма НДС 10%, руб. (тег 1103);Сумма НДС 20%, руб. (тег 1102);"
mark = "#analyse:link$"

bindfildfromheader = "regnumkkt"
bindfildfromtable = "Регистрационный номер ККТ"












