[[template.ofd]]
num = 1
name = "ofdru"
descr = "ofd.ru - петер"
[[template.ofd]]
num = 2
name = "firstofd"
descr = "1-ofd.ru - первый ОФД"
[[template.ofd]]
num = 3
name = "conturofd"
descr = "контур ОФД"
[[template.ofd]]
num = 4
name = "sbis"
descr = "СБИС"
[[template.ofd]]
num = 5
name = "platforma"
descr = "Платформа ОФД"

[fields.kkt]
inn = "инн фирмы"
regnumkkt = "регистрационный номер ККТ"
zavnumkkt = "заводской номер ККТ"
fnkkt = "номер ФН"
nameofkkt = "имя ККТ в ОФД"

[fields.check]
numSm = "номер смены"
fd = "номер ФД"
fp = "фискальный номер чека"
amountCheck = "сумма чека"
nal = "сумма наличными"
bez = "сумма безналичными"
credit = "сумма в расрочку"
avance = "сумма зачета апанса"
vstrechpredst = "сумма встречным представлением"
kassir = "имя кассира"
innkassir = "инн кассира"
date = "дата чека"
time = "время чека"
osn = "система налогообложения чека"
tag1054 = "тип чека: приход, расход, возврат прихода, возврат расхода"
typeCheck = "чек, коррекция и прочие"
link = "ссылка чека"
bindheadfieldkassa = "поле для связвание по кассе в таблице шапки"
bindheadfieldcheck = "поле для связывания по чеку в таблице шапк"

[fields.positions]
name = "название товара"
quantity = "количество товара"
price = "цена товара"
amountpos = "сумма товара"
predmet = "предмет расчета"
sposob = "способ расчета"
#stavkaNDSAll = "ставка НДС"
stavkaNDS = "ставка НДС"
stavkaNDS0 = "столбец суммы ставка НДС 0%"
stavkaNDS10 = "столбец суммы ставка НДС 10%"
stavkaNDS20 = "столбец суммы ставка НДС 20%"
stavkaNDS110 = "столбец суммы ставка НДС 110"
stavkaNDS120 = "столбец суммы ставка НДС 120"
mark = "марка"
bindposfieldkassa = "поле для связывания по кассе в таблице позций"
bindposfieldcheck = "поле для связывания по чеку в таблице позций"
bindposposfieldcheck = "поле для связывания по позициям в доплнительной таблице"

[fields.others]
markother = "марка"
bindotherfieldkassa = "поле для связывания по кассе в таблице позций"
bindotherfieldcheck = "поле для связывания по чеку в таблице позций"
bindotherposfieldcheck = "поле для связывания по позициям в таблице позиций"


[conturofd]
#-colFNCh 0 -colKassaNameCh 1 -colFDCh 2 -colFPCh 3 -col_kassir 4 -colDate 5 -colTypeCheck 6 -colTypeOper 7 -colNal 8 -colBez 9 -colAvPay 10 -colCred 11 -colObm 12 -colSumNDS20 13
fnkkt = "ФН №"
nameofkkt = "Касса"

fd = "ФД №"
amountCheck = ""
nal = "Наличными"
bez = "Безналичными"
credit = "Кредит"
avance = "Аванс"
vstrechpredst = "Обмен"
kassir = "Кассир"
date = "Дата чека"
osn = "СНО"
tag1054 = "Тип операции"
typeCheck = "Тип чека"
bindheadfieldkassa = "nameofkkt"
bindheadfieldcheck = "fd"

name = "Товар. Услуга"
quantity = "Кол-во"
price = "Цена, ₽"
amountpos = "Сумма, ₽"
predmet = "#analyse$Аванс"
sposob = "#analyse$Аванс"
#stavkaNDS = "#inv$НДС 20%;НДС 20/120;НДС 10%;НДС 10/110;Сумма с НДС 0%"
stavkaNDS0 = "#inv$Сумма с НДС 0%"
stavkaNDS10 = "#inv$НДС 10%"
stavkaNDS20 = "#inv$НДС 20%"
stavkaNDS110 = "#inv$НДС 10/110"
stavkaNDS120 = "#inv$НДС 20/120"
bindposfieldkassa = "Название кассы"
bindposfieldcheck = "ФД №"

[firstofd]
#-colFNCh 5 -colRegCh 2 -colKassaNameCh -1 -colFDCh 14 -colFPCh 15 -col_kassir 11 -col_Inn_kassir 12 -colDate 16 -colTypeCheck -1 -colTypeOper 19 -colNal 32 -colBez 33 -colAvPay 34 -colCred 35 -colObm 36 -colSumNDS20 28 -colName 6 -colQuant 8 -colPrice 7 -colAmountPos 9 -colSummPrepay -1 -colKassaNamePos 0 -colFDPos -1 -colPred 5
regnumkkt = "Регистрационный номер ККТ (1037)"
fnkkt = "Номер ФН (1041)"

#numSm = "Номер смены (1038)"
fd = "Номер ФД (1040)"
fp = "ФПД (1077)"
amountCheck = "Сумма расчета по чеку без НДС (1105)"
nal = "Сумма по чеку (БСО) наличными (1031)"
bez = "Сумма по чеку (БСО) безналичными (1081)"
credit = "Сумма по чеку (БСО) постоплатой (в кредит) (1216)"
avance = "Сумма по чеку (БСО) предоплатой (зачетом аванса и (или) предыдущих платежей) (1215)"
vstrechpredst = "Сумма по чеку (БСО) встречным предоставлением (1217)"
kassir = "Кассир (1021)"
innkassir = "ИНН кассира (1203)"
date = "Дата, время (1012)"
osn = "Применяемая система налогообложения (1055)"
tag1054 = "Тип документа. Признак расчета (1054)"
bindheadfieldkassa = "regnumkkt"
bindheadfieldcheck = "fd"

name = "Наименование предмета расчета (1030)"
quantity = "Количество предмета расчета (1023)"
price = "Цена за единицу предмета расчета с учетом скидок и наценок (1079)"
amountpos = "Стоимость предмета расчета с учетом скидок и наценок (1043)"
predmet = "Признак предмета расчета (1212)"
sposob = "#inv$Предоплата 100%;Частичная предоплата;Аванс;Полный расчет;Частичный расчет и кредит;Оплата кредита"
#stavkaNDSAll = "#inv$Сумма расчета по чеку с НДС по ставке 0% (1104);Сумма НДС чека по ставке 10% (1103);Сумма НДС чека по ставке 20% (1102);Сумма НДС чека по расч. ставке 10/110 (1107);Сумма НДС чека по расч. ставке 20/120 (1106)"
stavkaNDS0 = "#inv$Сумма расчета по чеку с НДС по ставке 0% (1104)"
stavkaNDS10 = "#inv$Сумма НДС чека по ставке 10% (1103)"
stavkaNDS20 = "#inv$Сумма НДС чека по ставке 20% (1102)"
stavkaNDS110 = "#inv$Сумма НДС чека по расч. ставке 10/110 (1107)"
stavkaNDS120 = "#inv$Сумма НДС чека по расч. ставке 20/120 (1106)"
#mark = "КТ GS1.М (1305)"
bindposfieldkassa = "Регистрационный номер ККТ (1037)"
bindposfieldcheck = "#analyse$Номер чека" #//0006989495006718_7280440500080718_5045
bindposposfieldcheck = "name"
#[fields.others]
markother = "КТ GS1.М (1305)"
bindotherfieldkassa = "Регистрационный номер ККТ (1037)"
bindotherfieldcheck = "#analyse$Номер чека"
bindotherposfieldcheck = "Наименование предмета расчета (1030)"

[ofdru]
#-colFNCh 1 -colRegCh 0 -colKassaNameCh -1 -colFDCh 15 -colFPCh -1 -col_kassir -1 -col_Inn_kassir -1 -colDate 16 -colTypeCheck -1 -colTypeOper -1 -colNal -1 -colBez -1 -colAvPay -1 -colCred -1 -colObm -1 -colSumNDS20 -1 -colName 0 -colQuant 5 -colPrice 4 -colAmountPos 6 -colSummPrepay -1 -colKassaNamePos 22 -colFDPos 32 -colPred 1 -colSpsRash 3 -colFPTovTabl 11 -col_kassirTov 28 -col_Inn_kassirTov -1 -colTypeCheckTov 2 -colNalTob 12 -colBezTov 13 -colAvPayTov 14 -colCredTov 15 -colObmTov 16 -colLinkOnCheck 30
regnumkkt = "Регистрационный номер ККТ"
fnkkt = "Заводской номер ФН"

fd = "Номер ФД"
fp = "#inv$ФПД"
nal = "#inv#analyse$Расчет по чеку наличными (тег 1031)"
bez = "#inv#analyse$Расчет по чеку безналичными (тег 1081)"
credit = "#inv#analyse$Расчет по чеку с постоплатой (тег 1216)"
avance = "#inv#analyse$Расчет по чеку предоплатой / зачетом аванса (тег 1215)"
vstrechpredst = "#inv#analyse$Расчет по чеку встречным предоставлением (тег 1217)"
kassir = "#inv$Кассир"
date = "Дата создания документа"
osn = "#analyse:link"
tag1054 = "#inv$Признак расчета (тег 1054)"
link = "#inv$Ссылка на документ" #Имя кассы"
bindheadfieldkassa = "regnumkkt"
bindheadfieldcheck = "fd"

name = "Наименование товаров и услуг (тег 1030)"
quantity = "Количество предметов расчета (тег 1023)"
price = "Цена за единицу предмета расчета с учетом скидок и наценок (тег 1079)"
amountpos  = "Стоимость предмета расчета с учетом скидок и наценок (тег 1043)"
predmet = "Признак предмета расчета (тег 1212)"
sposob = "Признак способа расчета (тег 1214)"
stavkaNDS0 = "Сумма НДС 0%, руб. (тег 1104)"
stavkaNDS10 = "Сумма НДС 10%, руб. (тег 1103)"
stavkaNDS20 = "Сумма НДС 20%, руб. (тег 1102)"
#stavkaNDSAll = "Сумма НДС 0%, руб. (тег 1104);Сумма НДС 10%, руб. (тег 1103);Сумма НДС 20%, руб. (тег 1102)"
mark = "#analyse:link$"
bindposfieldkassa = "Регистрационный номер ККТ"
bindposfieldcheck = "Номер фискального документа"

[sbis]
#[fields.kkt]
inn = "ИНН"
regnumkkt = "Рег. № ККТ"
zavnumkkt = "Зав. № ККТ"
fnkkt = "Зав. № ФН"
#[fields.check]
numSm = "№ смены"
fd = "№ ФД"
fp = "ФП"
amountCheck = "Сумма"
nal = "Наличными"
bez = "Безналичными"
credit = "Кредит"
avance = "Аванс"
vstrechpredst = "Обмен"
kassir = "Кассир"
#innkassir = "инн кассира"
date = "Дата и время"
#time = "время чека"
osn = "Система налогообложения"
tag1054 = "Тип операции"
typeCheck = "Тип документа"
#link = "ссылка чека"
bindheadfieldkassa = "regnumkkt"
bindheadfieldcheck = "fd"
#[fields.positions]
name = "Наименование предмета расчета"
quantity = "Количество"
price = "Цена"
amountpos = "Стоимость"
#predmet = "предмет расчета"
#sposob = "способ расчета"
##stavkaNDSAll = "ставка НДС"
stavkaNDS0 = "Сумма с НДС 0%"
stavkaNDS10 = "НДС 10%"
stavkaNDS20 = "НДС 20%"
stavkaNDS110 = "НДС 10/110"
stavkaNDS120 = "НДС 20/120"
#mark = "марка"
bindposfieldkassa = "Рег. № ККТ"
bindposfieldcheck = "№ ФД"

[platforma]
#[fields.kkt]
#inn = "инн фирмы"
regnumkkt = "РНМ"
#zavnumkkt = "заводской номер ККТ"
fnkkt = "Номер ФН"
#nameofkkt = "имя ККТ в ОФД"
#[fields.check]
#numSm = "номер смены"
fd = "Номер документа"
fp = "ФП"
#amountCheck = "сумма чека"
nal = "Наличными"
bez = "Электронными"
credit = "Постоплата(кредитами)"
avance = "Зачет предоплаты (аванса)"
vstrechpredst = "Встречными представлениями"
kassir = "Кассир"
innkassir = "ИНН кассира"
date = "Дата/время"
#time = "время чека"
osn = "Тип налогообложения"
tag1054 = "Признак расчета"
typeCheck = "Тип ФД"
link = "Посмотреть чек"
bindheadfieldkassa = "regnumkkt"
bindheadfieldcheck = "fd"
#[fields.positions]
name = "Наименование"
quantity = "Количество единиц измерения в чеке"
price = "Цена товара"
amountpos = "Сумма товара"
predmet = "Признак предмета расчета (тег 1212)"
sposob = "Признак способа расчета (тег 1214)"
#stavkaNDSAll = "ставка НДС"
stavkaNDS = "Ставка НДС по товару"
stavkaNDS0 = "Сумма НДС 0% по чеку"
stavkaNDS10 = "Сумма НДС 10% по чеку"
stavkaNDS20 = "Сумма НДС 20% по чеку"
stavkaNDS110 = "Сумма НДС 10/110% по чеку"
stavkaNDS120 = "Сумма НДС 20/120% по чеку"
#mark = "марка"
bindposfieldkassa = "РНМ"
bindposfieldcheck = "Номер документа"
bindposposfieldcheck = "Номер товара в чеке"
#[fields.others]
markother = "Код маркировки"
bindotherfieldkassa = "РНМ"
bindotherfieldcheck = "Номер ФД"
bindotherposfieldcheck = "Позиция в чеке"
